package firewall

import "testing"

func TestRulesetSnapshotIDIgnoresVolatileIptablesSaveOutput(t *testing.T) {
	base := `# Generated by iptables-save v1.8.10 on Thu May 28 01:02:03 2026
*filter
:INPUT ACCEPT [0:0]
:FORWARD DROP [0:0]
:OUTPUT ACCEPT [0:0]
-A INPUT -j ACCEPT
COMMIT
# Completed on Thu May 28 01:02:03 2026
`
	volatile := `# Generated by iptables-save v1.8.10 on Thu May 28 01:02:04 2026
*filter
:INPUT ACCEPT [123:456]
:FORWARD DROP [7:89]
:OUTPUT ACCEPT [10:11]
-A INPUT -c 44 5555 -j ACCEPT
COMMIT
# Completed on Thu May 28 01:02:04 2026
`

	if rulesetSnapshotID(base) != rulesetSnapshotID(volatile) {
		t.Fatal("expected comments and counters to be ignored in ruleset snapshot")
	}
}

func TestRulesetSnapshotIDChangesWhenRulesChange(t *testing.T) {
	base := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -j ACCEPT
COMMIT
`
	changed := `*filter
:INPUT ACCEPT [0:0]
-A INPUT -j DROP
COMMIT
`

	if rulesetSnapshotID(base) == rulesetSnapshotID(changed) {
		t.Fatal("expected rule changes to produce a different ruleset snapshot")
	}
}
